version: '3'

services:
  db:
     image: mysql:5.7
     volumes:
       - dbdata:/var/lib/mysql
     restart: always
     environment:
       MYSQL_ROOT_PASSWORD: tdspassword
       MYSQL_DATABASE: tds
       MYSQL_USER: tdsuser
       MYSQL_PASSWORD: tdspassword
  web:
    build: .
    command: python3 manage.py runserver 0.0.0.0:8000
    volumes:
      - .:/code
    ports:
      - "8000:8000"
    depends_on:
      - db